const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function boot(profile={playerName:'Thỏ',stars:100,petAdopt:{earnedAt:'2026-10-07T00:00:00Z',runId:'bow',score:15,total:15}}){
 let store=JSON.parse(JSON.stringify(profile)),fail=false,drop=false,writes=0;
 const Storage={load:()=>JSON.parse(JSON.stringify(store)),getActiveName:()=>store.playerName||'',save:p=>{if(!fail){store=JSON.parse(JSON.stringify(p));if(drop)delete store.petWardrobe;writes++;}}};
 const box={window:{},Storage,console};vm.createContext(box);
 for(const file of ['pet-room.js','pet-accessories.js','pet.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file),'utf8'),box);
 return {P:box.window.Pet,A:box.window.PetAccessories,read:()=>store,Storage,box,writes:()=>writes,fail:()=>fail=true,drop:()=>drop=true};
}
let count=0;function test(name,fn){fn();console.log('OK '+name);count++;}
test('no pet / guest cannot buy',()=>{const b=boot();assert.equal(b.P.buyAccessory('bow-blue').error,'no-pet');assert.equal(b.read().stars,100);const g=boot({playerName:'',stars:100});assert.equal(g.P.buyAccessory('bow-blue').error,'guest');});
test('buy once, duplicate request and second purchase cannot charge twice',()=>{const b=boot();b.P.adopt('Bông');assert.ok(b.P.buyAccessory('bow-blue','once').ok);assert.equal(b.read().stars,50);assert.equal(b.P.buyAccessory('bow-blue','once').error,'duplicate');assert.equal(b.P.buyAccessory('bow-blue','twice').error,'owned');assert.equal(b.read().stars,50);assert.equal(b.P.wardrobe().equipped.head,'bow-blue');});
test('remove / equip free, fresh stars and wardrobe survive reload',()=>{const b=boot();b.P.adopt('Bông');b.read().stars=180;b.P.buyAccessory('bow-blue');assert.equal(b.read().stars,130);b.P.removeAccessory('head');assert.equal(b.P.wardrobe().equipped.head,null);b.P.equipAccessory('bow-blue');assert.equal(b.read().stars,130);const c=boot(b.read());assert.equal(c.P.wardrobe().equipped.head,'bow-blue');});
test('bad IDs / wrong slot / unowned equipment are ignored safely',()=>{const b=boot();b.P.adopt('Bông');assert.equal(b.P.equipAccessory('bow-blue').error,'not-owned');assert.equal(b.P.buyAccessory('constructor').error,'id');b.read().petWardrobe={owned:['bow-blue','bad','bow-blue'],equipped:{head:'bad',neck:'bow-blue',back:'constructor'}};assert.deepEqual(JSON.parse(JSON.stringify(b.P.wardrobe())),{v:1,owned:['bow-blue'],equipped:{head:null,neck:null,back:null}});});
test('insufficient stars / failed save do not report successful purchase',()=>{const b=boot();b.P.adopt('Bông');b.read().stars=49;assert.equal(b.P.buyAccessory('bow-blue').error,'stars');b.read().stars=100;b.fail();assert.equal(b.P.buyAccessory('bow-blue').error,'save');assert.equal(b.read().stars,100);assert.deepEqual(JSON.parse(JSON.stringify(b.P.wardrobe().owned)),[]);});
test('readback verifies wardrobe itself, not only stars/pet',()=>{const b=boot();b.P.adopt('Bông');b.drop();assert.equal(b.P.buyAccessory('bow-blue').error,'save');});
test('old pet v1 transaction preserves separately stored wardrobe',()=>{const b=boot();b.P.adopt('Bông');b.P.buyAccessory('bow-blue');const before=JSON.stringify(b.read().petWardrobe),old={window:{},Storage:b.Storage,console};vm.createContext(old);vm.runInContext(fs.readFileSync(path.join(__dirname,'fixtures/pet-flat-v1.js'),'utf8'),old);assert.ok(old.window.Pet.feed('kibble').ok);assert.equal(JSON.stringify(b.read().petWardrobe),before);});
test('growth keeps bow ownership/equip and metadata covers 3 stages x 16 frames',()=>{const b=boot();b.P.adopt('Bông');b.P.buyAccessory('bow-blue');for(let stage=0;stage<3;stage++){b.read().pet.stage=stage;b.read().pet.growth=[0,10,30][stage];assert.equal(b.P.wardrobe().equipped.head,'bow-blue');for(let frame=0;frame<16;frame++)for(const slot of b.A.SLOTS){const a=b.A.anchor(stage,frame,[0,0,300,300],slot);assert.ok(Number.isFinite(a.x)&&Number.isFinite(a.y));assert.ok(['front','behind'].includes(a.layer));assert.equal(a.visible,frame!==3);}}});
console.log(count+' accessory tests passed');
