const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/pet.js'),'utf8');
function boot(profile={playerName:'Thỏ',stars:100,petAdopt:{earnedAt:'2026-10-07T00:00:00Z',runId:'earned-test',score:0,total:15}}){let saved=JSON.parse(JSON.stringify(profile)),writes=0,fail=false;const box={window:{},console,Storage:{load:()=>JSON.parse(JSON.stringify(saved)),getActiveName:()=>saved.playerName||'',save:p=>{if(!fail){saved=JSON.parse(JSON.stringify(p));writes++;}}}};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/pet-room.js'),'utf8'),box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/pet-accessories.js'),'utf8'),box);vm.runInContext(source,box);const P=box.window.Pet;return {P,read:()=>saved,writes:()=>writes,fail:()=>fail=true};}
let count=0;function test(name,fn){fn();count++;console.log('OK',name);}
test('guest cannot adopt',()=>{const b=boot({playerName:'',stars:100});assert.equal(b.P.adopt('Cún').error,'guest');assert.equal(b.writes(),0)});
test('adopt once / no duplicate charge',()=>{const b=boot();assert.ok(b.P.adopt('Cún','a').ok);assert.equal(b.P.adopt('Cún','a').error,'duplicate');assert.equal(b.writes(),1)});
test('fresh profile avoids stale stars',()=>{const b=boot();b.P.adopt('Cún');b.read().stars=50;b.P.buyFood('kibble','a');assert.equal(b.read().stars,40)});
test('food purchase same request cannot charge twice',()=>{const b=boot();b.P.adopt('Cún');assert.ok(b.P.buyFood('kibble','a').ok);assert.equal(b.P.buyFood('kibble','a').error,'duplicate');assert.equal(b.read().stars,90);assert.equal(b.read().pet.bag.kibble,7)});
test('3 meals/day, full keeps food; next day continues',()=>{const b=boot();b.P.adopt('Cún');for(let i=0;i<3;i++)assert.ok(b.P.feed('kibble','feed'+i).ok);assert.equal(b.P.feed('kibble','fourth').error,'full');assert.equal(b.read().pet.bag.kibble,3);b.P.dateKey=()=> '2099-01-02';assert.ok(b.P.feed('kibble','next').ok);assert.equal(b.read().pet.growth,4);assert.equal(b.read().pet.day.meals,1)});
test('thresholds and stage never decreases',()=>{const b=boot();b.P.adopt('Cún');b.read().pet.growth=9;b.read().pet.bag.kibble=2;assert.ok(b.P.feed('kibble','f').celebrate);assert.equal(b.read().pet.stage,1);b.read().pet.growth=29;assert.ok(b.P.feed('kibble','f2').celebrate);assert.equal(b.read().pet.stage,2);b.read().pet.growth=0;assert.equal(b.P.snapshot().stage,2)});
test('owned decoration cannot charge twice',()=>{const b=boot();b.P.adopt('Cún');assert.ok(b.P.buyItem('bed-blue','buy').ok);assert.equal(b.P.buyItem('bed-blue','buy2').error,'owned');assert.equal(b.read().stars,50);assert.ok(b.P.equip('bed-default').ok);assert.ok(b.P.equip('bed-blue').ok);assert.equal(b.read().stars,50)});
test('unknown ids / corrupt values normalized',()=>{const b=boot();b.P.adopt('Cún');const raw=b.read().pet;raw.room.slots.bed='unknown';raw.bag.kibble=-5;raw.owned=['constructor','missing'];const p=b.P.snapshot();assert.equal(p.room.bed,'bed-default');assert.equal(p.bag.kibble,0);assert.equal(p.owned.length,0);assert.equal(b.P.buyFood('constructor').error,'id');assert.equal(b.P.buyItem('toString').error,'id')});
test('failed save does not claim success or run growth',()=>{const b=boot();b.P.adopt('Cún');b.fail();assert.equal(b.P.buyFood('kibble','b').error,'save');assert.equal(b.read().stars,100);assert.equal(b.read().pet.bag.kibble,6)});
test('profile backup / reload preserves pet',()=>{const b=boot();b.P.adopt('Bông');b.P.buyFood('kibble','buy');b.P.feed('kibble','f');const c=boot(JSON.parse(JSON.stringify(b.read())));assert.equal(c.P.snapshot().name,'Bông');assert.equal(c.P.snapshot().growth,1);assert.equal(c.read().stars,90)});
test('locked prices reject purchase',()=>{const b=boot();b.P.adopt('Cún');b.P.FOODS.treat.price=null;b.P.ITEMS['rug-pink'].price=null;assert.equal(b.P.buyFood('treat').error,'price-pending');assert.equal(b.P.buyItem('rug-pink').error,'price-pending')});
test('adoption requires completed challenge; starter food awarded once',()=>{const b=boot({playerName:'Thỏ',stars:100});assert.equal(b.P.adopt('Cún').error,'challenge');b.read().petAdopt={earnedAt:new Date().toISOString(),runId:'completed',score:0,total:15};assert.ok(b.P.adopt('Cún').ok);assert.equal(b.read().stars,100);assert.equal(b.read().pet.bag.kibble,6);assert.ok(b.read().petAdopt.usedAt);assert.equal(b.P.adopt('Cún').error,'adopted');assert.equal(b.read().pet.bag.kibble,6)});
test('broken pet archived once even when action cannot continue',()=>{const b=boot();b.P.adopt('Bông');b.read().pet.kind='old-invalid-kind';const raw=JSON.parse(JSON.stringify(b.read().pet));assert.equal(b.P.feed('kibble').error,'no-pet');assert.deepEqual(b.read().petBroken,raw);assert.equal(b.read().pet,null);b.read().pet={kind:'another-invalid',name:'Khác'};b.P.visit();assert.deepEqual(b.read().petBroken,raw)});
test('used adoption right can recover absent or broken pet and preserve name',()=>{const b=boot();b.P.adopt('Bông');b.read().pet.kind='bad';assert.ok(b.P.adoptionRight());assert.equal(b.P.recoveryName(),'Bông');assert.ok(b.P.adopt(b.P.recoveryName(),'recover').ok);assert.equal(b.P.snapshot().name,'Bông');assert.equal(b.read().petBroken.name,'Bông');assert.equal(b.P.adopt('Again').error,'adopted');assert.equal(b.P.adoptionRight(),null);b.read().pet=null;assert.ok(b.P.adoptionRight());assert.equal(b.P.recoveryName(),'Bông');assert.ok(b.P.adopt(b.P.recoveryName(),'recover2').ok)});
test('approved shop prices and equal growth from both foods',()=>{const b=boot();b.P.adopt('Bông');assert.equal(b.P.FOODS.kibble.price,10);assert.equal(b.P.FOODS.treat.price,15);assert.ok(Object.values(b.P.ITEMS).every(x=>x.price===(x.free?0:50)));assert.ok(b.P.buyFood('treat','t').ok);assert.equal(b.read().stars,85);assert.ok(b.P.feed('treat','ft').ok);assert.equal(b.read().pet.growth,1);assert.ok(b.P.feed('kibble','fk').ok);assert.equal(b.read().pet.growth,2);b.read().stars=9;assert.equal(b.P.buyFood('kibble','low').error,'stars');assert.equal(b.read().stars,9)});
console.log(count+' pet tests passed');
